version: 1
jobs:
  main:
    steps:
      - goto: https://weather.com/weather/today/l/2180f6103515df172f8e1ed296888bca1178ad1ef792142fb89556f2a1395ba2
      - title
      - text:
          selector: .today_nowcard-temp span
          type: number
          as: temp_number
      - text:
          selector: .today_nowcard-temp span
          type: string
          as: temp_string
      - text:
          selector: .today_nowcard-temp span
          type: integer
          as: temp_integer
      - text:
          selector: .today_nowcard-temp span
          type: float
          as: temp_float